import { FilterProvider } from "@/context/filter_context";
import { ProductsProvider } from "@/context/products_context";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsProvider>
          <FilterProvider>{children}</FilterProvider>
        </ProductsProvider>
      </body>
    </html>
  );
}
